# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_auto_20181120_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=0, upload_to='user_images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
