# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_auto_20181227_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=b''),
        ),
    ]
