# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_auto_20190107_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='misc_image',
            field=models.ImageField(blank=True, upload_to='misc'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
