# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0006_auto_20190114_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_photo', to='photography.Album'),
        ),
    ]
