# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_auto_20190116_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_photo', to='photography.Album'),
        ),
    ]
