# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-16 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0009_auto_20190116_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_photo', to='photography.Album'),
            preserve_default=False,
        ),
    ]
