# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0015_auto_20190125_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='photo',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics'),
        ),
    ]
