# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-28 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0017_auto_20190127_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profilepic',
        ),
    ]
