# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0018_remove_photo_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='misc_image',
            field=models.ImageField(blank=True, default=1, upload_to='misc'),
            preserve_default=False,
        ),
    ]
