# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-28 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0019_auto_20190128_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='misc_image',
            field=models.ImageField(blank=True, null=True, upload_to='misc'),
        ),
    ]
