# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0022_auto_20190128_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='misc_image',
            field=django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to='misc'),
        ),
    ]
