# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-13 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0023_auto_20190204_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='misc_image',
        ),
    ]
