# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0024_remove_photo_misc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
